services:
  - type: web
    name: recomap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mapproject.wsgi:application --chdir .
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: recomap.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: recomap-db
          property: connectionString
    autoDeploy: true
    branch: develop
