# Generated by Django 5.1.7 on 2025-03-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
