# Generated by Django 5.1.7 on 2025-03-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_spot_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='spot',
            name='hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='spot',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
