# Generated by Django 5.1.7 on 2025-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_spot_genre_spot_hours_spot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='icon',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
