# Generated by Django 5.1.7 on 2025-03-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_spot_icon'),
        ('map', '0005_alter_custommap_user'),
    ]

    operations = [
    ]
