# Generated by Django 5.1.7 on 2025-04-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_custommap_description_custommap_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommap',
            name='is_system_default',
            field=models.BooleanField(default=False),
        ),
    ]
